# Generated by Django 5.2.8 on 2025-11-14 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolclass",
            options={
                "ordering": ["name"],
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["name"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["name"],
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="name",
            field=models.CharField(
                help_text="Name of the class (e.g., 'Class 10-A')",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary teacher assigned to this class",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="core.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_assigned",
            field=models.ForeignKey(
                help_text="The class to which the student is assigned",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                help_text="Unique email address", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                help_text="Full name of the student", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(
                help_text="Unique roll number", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                help_text="Unique email address", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(
                help_text="Full name of the teacher", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Contact number (optional)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(
                help_text="Subject taught by the teacher", max_length=100
            ),
        ),
    ]
